version: '3.1'
services:

  # https://www.docker.elastic.co/

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    ports:
    - "9200:9200"
    environment:
    - discovery.type=single-node