version: '3.1'
services:

  # https://www.docker.elastic.co/

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    ports:
    - "9200:9200"
    - "9300:9300"
    container_name: jetagent_elasticsearch
    environment:
    - discovery.type=single-node
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9200"]
        interval: 30s
        timeout: 10s
        retries: 5
   
   backend:
    image: jetagent 
    ports:
    - "8080:8080"
    container_name: jetagent_backend
    depends_on:
    - elasticsearch
    links:
    - elasticsearch
    