version: '3.1'

services:
    elasticsearch:
        image: 'docker.elastic.co/elasticsearch/elasticsearch:6.4.2'
        ports:
            - '9200:9200'
            - '9300:9300'
        container_name: jetagent_elasticsearch
        environment:
            - discovery.type=single-node
